---
- name: Install remote Facts
  hosts: web
  vars:
          remote_dir: /etc/ansible/facts.d
          fact_file: custom.fact
  tasks:
          - name: Create remote directory
            file:
                    state: directory
                    recurse: yes
                    path: "{{ remote_dir }}"
          - name: Install the custom facts
            copy:
                    src: "{{ fact_file }}"
                    dest: "{{ remote_dir }}"
...
