---
- name: Install apache and start the service
  hosts: web
  tasks:
          - name: Install the required package
            yum:
                    name: "{{ ansible_facts['ansible_local']['custom']['general']['package']}}"
                    state: latest
          - name: Start and enable the service
            service:
                    name: "{{ ansible_facts['ansible_local']['custom']['general']['service']}}"
                    state: "{{ ansible_facts['ansible_local']['custom']['general']['state']}}"
                    enabled: "{{ ansible_facts['ansible_local']['custom']['general']['enable']}}"
...
